// Code generated by mockery v2.49.1. DO NOT EDIT.

package mock

import (
	adminmodels "github.com/SolomonAHailu/one-card-system/models/adminmodels"
	mock "github.com/stretchr/testify/mock"

	repositories "github.com/SolomonAHailu/one-card-system/skleton/repositories"
)

// GetAllDevicesUsecase is an autogenerated mock type for the GetAllDevicesUsecase type
type GetAllDevicesUsecase struct {
	mock.Mock
}

// GetAllDevices provides a mock function with given fields: getAllDevices
func (_m *GetAllDevicesUsecase) GetAllDevices(getAllDevices *repositories.GetAllDeviceRequest) ([]adminmodels.Devices, error) {
	ret := _m.Called(getAllDevices)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDevices")
	}

	var r0 []adminmodels.Devices
	var r1 error
	if rf, ok := ret.Get(0).(func(*repositories.GetAllDeviceRequest) ([]adminmodels.Devices, error)); ok {
		return rf(getAllDevices)
	}
	if rf, ok := ret.Get(0).(func(*repositories.GetAllDeviceRequest) []adminmodels.Devices); ok {
		r0 = rf(getAllDevices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]adminmodels.Devices)
		}
	}

	if rf, ok := ret.Get(1).(func(*repositories.GetAllDeviceRequest) error); ok {
		r1 = rf(getAllDevices)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetAllDevicesUsecase creates a new instance of GetAllDevicesUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAllDevicesUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAllDevicesUsecase {
	mock := &GetAllDevicesUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
