// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	adminmodels "github.com/SolomonAHailu/one-card-system/models/adminmodels"
	adminRepo "github.com/SolomonAHailu/one-card-system/skeletons/repo/admincontrollers"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: createUser
func (_m *UserRepository) CreateUser(createUser *adminRepo.CreateUserRequest) (adminmodels.Users, error) {
	ret := _m.Called(createUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 adminmodels.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) (adminmodels.Users, error)); ok {
		return rf(createUser)
	}
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) adminmodels.Users); ok {
		r0 = rf(createUser)
	} else {
		r0 = ret.Get(0).(adminmodels.Users)
	}

	if rf, ok := ret.Get(1).(func(*adminRepo.CreateUserRequest) error); ok {
		r1 = rf(createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserById provides a mock function with given fields: createUser
func (_m *UserRepository) DeleteUserById(createUser *adminRepo.CreateUserRequest) (adminmodels.Users, error) {
	ret := _m.Called(createUser)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserById")
	}

	var r0 adminmodels.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) (adminmodels.Users, error)); ok {
		return rf(createUser)
	}
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) adminmodels.Users); ok {
		r0 = rf(createUser)
	} else {
		r0 = ret.Get(0).(adminmodels.Users)
	}

	if rf, ok := ret.Get(1).(func(*adminRepo.CreateUserRequest) error); ok {
		r1 = rf(createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByRoleId provides a mock function with given fields: createUser
func (_m *UserRepository) GetUsersByRoleId(createUser *adminRepo.CreateUserRequest) (adminmodels.Users, error) {
	ret := _m.Called(createUser)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByRoleId")
	}

	var r0 adminmodels.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) (adminmodels.Users, error)); ok {
		return rf(createUser)
	}
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) adminmodels.Users); ok {
		r0 = rf(createUser)
	} else {
		r0 = ret.Get(0).(adminmodels.Users)
	}

	if rf, ok := ret.Get(1).(func(*adminRepo.CreateUserRequest) error); ok {
		r1 = rf(createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserById provides a mock function with given fields: createUser
func (_m *UserRepository) UpdateUserById(createUser *adminRepo.CreateUserRequest) (adminmodels.Users, error) {
	ret := _m.Called(createUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserById")
	}

	var r0 adminmodels.Users
	var r1 error
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) (adminmodels.Users, error)); ok {
		return rf(createUser)
	}
	if rf, ok := ret.Get(0).(func(*adminRepo.CreateUserRequest) adminmodels.Users); ok {
		r0 = rf(createUser)
	} else {
		r0 = ret.Get(0).(adminmodels.Users)
	}

	if rf, ok := ret.Get(1).(func(*adminRepo.CreateUserRequest) error); ok {
		r1 = rf(createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
